age = int(input("Enter your age: "))

if age < 5:
    print("You are a Toddler.")
        else:
                if age <= 12:
                                print("You are a Child.")
                                                    else:
                                                                                if age <= 19:
                                                                                                                        print("You are a Teenager.")
                                                                                                                                                                        else:
                                                                                                                                                                                                                                    if age <= 35:
                                                                                                                                                                                                                                                                                                                print("You are a Young Adult.")
                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if age <= 60:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("You are Middle-Aged.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("You are a Senior.")